<?php

/**
 * Author: Peter Dragicevic [peter-91@hotmail.de]
 * Authors-Website: http://petschko.org/
 * Date: 21.04.2016
 * Time: 12:58
 * Update: -
 * Version: 0.0.1
 *
 * Licence: http://creativecommons.org/licenses/by-sa/4.0/
 * You are free to use this!
 *
 * Notes: Class for easily creating Input Buttons
 */

/**
 * Class InputButton
 */
class InputButton extends InputField {
	// @Overwrite
	public function __construct($name, $type, $required, $dataType, $disabled, $otherHTMLAttr, $value) {
		parent::__construct($name, $type, $required, $dataType, $disabled, $otherHTMLAttr, $value); // TODO: Change the autogenerated stub
	}

	// @Overwrite
	public function output() {
		parent::output(); // TODO: Change the autogenerated stub
	}
}
